# CoreVisitor - Applicazione Gestione Visitatori
# Usa i servizi condivisi da CoreServices
#
# IMPORTANTE: Prima di avviare questo stack, assicurati che i servizi condivisi siano attivi:
#   cd ../CoreServices && docker-compose up -d
#
# Avvio:   docker-compose up -d
# Stop:    docker-compose down
# Logs:    docker-compose logs -f
# Rebuild: docker-compose up -d --build

services:
  # Backend API (NestJS)
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: corevisitor-backend
    restart: unless-stopped
    environment:
      # Database - usa il MySQL condiviso da CoreServices
      DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@core-mysql:3306/${MYSQL_DATABASE}

      # JWT
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}

      # MinIO - usa il MinIO condiviso da CoreServices
      MINIO_ENDPOINT: core-minio
      MINIO_PORT: ${MINIO_PORT}
      MINIO_USE_SSL: ${MINIO_USE_SSL}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME}

      # Meilisearch - usa il Meilisearch condiviso da CoreServices
      MEILISEARCH_HOST: http://core-meilisearch:7700
      MEILISEARCH_API_KEY: ${MEILISEARCH_API_KEY}

      # App
      APP_PORT: ${APP_PORT}
      APP_URL: ${APP_URL}
      NODE_ENV: production
    ports:
      - "3006:3006"
    networks:
      - core-network  # Usa la network condivisa
    command: sh -c "npx prisma migrate deploy || true && node dist/main"

  # Frontend (Next.js)
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    container_name: corevisitor-frontend
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      NODE_ENV: production
    ports:
      - "3005:3000"
    depends_on:
      - backend
    networks:
      - core-network  # Usa la network condivisa

# Nginx è gestito centralmente da CoreServices (core-nginx)
# Accesso: http://localhost:83

# Usa la network esterna creata da CoreServices
networks:
  core-network:
    external: true
    name: core-network
